apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpenim
  labels:
    app: castello-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: castello-front
  template:
    metadata:
      labels:
        app: castello-front
    spec:
      containers:
      - name: castello
        image: ahmetgrbzz/bookstore:1.0
        ports:
        - containerPort: 3000
